import type { Metadata } from "next";
import {Poppins } from "next/font/google";
import "./globals.css";
import ReactQuery from "@/lib/react-query";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/fragments/sidebar-app";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // bisa disesuaikan
  variable: '--font-poppins',          // optional
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#F7F8FA] min-h-screen`}>
        <ReactQuery>
            {children}
        </ReactQuery>
      </body>
    </html>
  );
}
